name: 'Hax Auto Renew'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 */1 * *'
jobs:
  hax_renew:
    runs-on: windows-2022
    
    steps:
      - name: 'Renewing Hax VPS ....' 
        run: |
          cmd /c curl -sSL -O https://raw.githubusercontents.com/taiyi747/ex1/main/HaxAutoReNew.exe
          cmd /c HaxAutoReNew.exe -user "5344302244" -password "131313Aa"
